encode:
  input: "samples/image.bmp"
  output: "samples/image_encode.bmp"
  text: "Shilo bob bob bibo bam top"

decode:
  input: "samples/image_encode.bmp"

compare:
  first: "samples/image.bmp"
  second: "samples/image_encode.bmp"
  output: "samples/image_compared.bmp"

eot: "KiHeu,6"
entry: 146
key: 4
op: blue