encode:
  input: "samples/sample_640×426.bmp"
  output: "samples/sample_640x426_encode.bmp"
  text: "Shilo bob bob bibo bam top"

decode:
  input: "samples/sample_640x426_encode.bmp"

compare:
  first: "samples/sample_640×426.bmp"
  second: "samples/sample_640x426_encode.bmp"
  output: "samples/sample_640x426_compared.bmp"

eot: "KiHeu,6"
entry: 146
key: 4
op: green